### ISSUE TITLE
Planejar a comunicação e validá-la com o time

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#1]
O plano de comunicação deve ser criado e todos os membros do time devem estar de acordocom o documentado

**Comment by fabiolamfleury** [comment]
A versão inicial do plano encontra-se em: https://github.com/fga-eps-mds/2018.2-GrupoMDIC/wiki/Plano-de-Comunica%C3%A7%C3%A3o

Falta definir o período das reuniões do cliente e validar o plano com o time.

Atualizado:
https://fga-eps-mds.github.io/2018.2-GrupoMDIC/docs/comunicacao

**Comment by fabiolamfleury** [comment]
@Joranhezon @SannyaArvelos @andrelucasf @caioiobs @riquekaique @vinicinolivera @rogerioo 
@MarcosNBJ @joao15victor08 

Por favor comentem nessa issue se vocês concordam com o documento e se comprometem com ele :)

**Comment by MarcosNBJ** [comment]
Concordo inteiramente com o proposto.

**Comment by andrelucasf** [comment]
Concordo plenamente!

**Comment by Joranhezon** [comment]
Concordo!

**Comment by kaiquebuilds** [comment]
Concordo!

**Comment by SannyaArvelos** [comment]
Concordo.

**Comment by joao15victor08** [comment]
Concordo.

**Comment by caioiobs** [comment]
Concordo!

**Comment by fabiolamfleury** [comment]
Apesar de faltarem 2 membros comentarem, foi considerado que houve prazo o suficiente para todos realizarem a leitura do documento e acredita-se que todos os integrantes do time possuem compromisso com a comunicação.
