### ISSUE TITLE
Configuração de repositório e ambiente do frontend

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#102]
## Descrição

Eu, como desenvolvedor, quero criar o ambiente de desenvolvimento do frontend, para que possa desenvolver a aplicação web do ComexStat.

## Tipo

- História técnica

## Critérios de aceitação

- [ ] O repositório deve ser criado
- [ ] Um projeto em angular 2 deve estar configurado
- [ ] A integração contínua deve contemplar front e back end

**Comment by viniciusoliveira96** [comment]
Foi decido usar apenas um repositorio com os dois projetos, backend e frontend

**Comment by viniciusoliveira96** [comment]
No momento, o docker esta com alguns problemas que estão sendo resolvidos
