### ISSUE TITLE
Configurar ambiente de homologação de frontend

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#109]
## Descrição

Eu, como um desenvolvedor, quero configurar um ambiente de frontend para que o cliente possa validá-lo.

## Tipo

- História técnica (#108)

## Critérios de aceitação

- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by SannyaArvelos** [comment]
Está configurado.
