### ISSUE TITLE
Elaborar documento de visão

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#11]
## Descrição

- Estudar conceito de comércios de bens e serviços e o MDIC

- Estudar o http://comexstat.mdic.gov.br/

- Estudar o que foi dito na issue https://github.com/fga-eps-mds/2018.2-GrupoMDIC/issues/2

**Comment by andrelucasf** [comment]
Galera no próprio site do comexstat tem uns tutoriais dos filtros de pesquisa. Quem quiser dar uma olhada: http://comexstat.mdic.gov.br/pt/tutorial

**Comment by rogerioo** [comment]
Começamos o documento de visão. 
Membros presentes: @MarcosNBJ, @andrelucasf, @Joranhezon

**Comment by rogerioo** [comment]
@Joranhezon @fabiolamfleury  Como a gente vai fazer a parte de recursos do produto?
Porque a gente ainda não tem isso bem definido

**Comment by Joranhezon** [comment]
Para isso, estudem o http://comexstat.mdic.gov.br/ e se baseiem nele. Tudo bem mudarmos e evoluirmos mais tarde, mas se baseiem por ele.

**Comment by kaiquebuilds** [comment]
Estou concluindo o tópico 3.6 (Principais necessidades dos usuários ou envolvidos.

**Comment by fabiolamfleury** [comment]
Após a reunião que será realizada dia 03/09/2018, este documento deve ser refinado para uma nova versão.

**Comment by Joranhezon** [comment]
Pessoal, o documento de visão já pode ser evoluído com base na issue #40.

**Comment by rogerioo** [comment]
Galera, bora se reunir umas 12:30 até o início da outra aula pra arrumar o documento com as novas especificações?

**Comment by andrelucasf** [comment]
Vamos, temos que finalizar o documento!

**Comment by rogerioo** [comment]
Gente, duas coisas:
* O cliente entra no documento de visão, na parte do "Resumo dos Envolvidos"?
* Eu preciso colocar na definição desse documento os acrônimos (tipo devops), se já está definido nas outras documentações?

**Comment by fabiolamfleury** [comment]
As dúvidas foram esclarecidas por telegram, as atualizações feitas e o PR aceito :) bom trabalho time
