### ISSUE TITLE
Realizar busca padrão para Comércio de Bens

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#141]
## Descrição

Eu, como usuário, gostaria de realizar uma busca padronizada relacionada à comércio de bens, para obter dados referentes à isso.

## Tipo

- História de Usuário

## Critérios de aceitação/Tasks

- [ ] Realizar requisição do Front para o Backend
- [ ] Criar range de busca por ano no Backend

**Comment by MarcosNBJ** [comment]
Pull request com o cumprimento do task faltante já realizado no repositório do FrontEnd

**Comment by Joranhezon** [comment]
As funcionalidades estão feitas, porém foram encontrados problemas no codeclimate e no travis, impossibilitando o fechamento dela e a tornando dívida para próxima Sprint.
