### ISSUE TITLE
Criar roadmap de cada papel

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#15]
## Descrição

- [ ] Devops

- [ ] Arquitetura

- [ ] Scrum master

- [ ] Product Owner

**Comment by fabiolamfleury** [comment]
Sobre o roadmap de scrum master:

Levantar indicadores (burndown de risco, quadro de conhecimento, pontos, custos)
Trabalhar em prol dos indicadores
Planejar, monitorar e controlar
Lidar com problemas de maneira explícita na Sprint sucessora
Planilha de riscos
Impor ritmo
Sempre trabalhar com dado
Levantar as métricas e quadro de conhecimento
Qualquer aspecto de conhecimento do projeto

**Comment by victorcmoura** [comment]
Isso aqui pode ser útil pra ajudá-los no roadmap de devops:
https://github.com/fga-eps-mds/A-Disciplina/blob/master/Devops/roadmap-devops.md

**Comment by rogerioo** [comment]
Papéis definidos [aqui](https://fga-eps-mds.github.io/2018.2-ComexStat/docs/processo)
