### ISSUE TITLE
Roadmap Release 2

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#150]
## Descrição

Eu, como Product Owner, gostaria de fazer o roadmap da release 2, de maneira que seja possível para o cliente e a equipe entenderem exatamente o que será entregue nesse ciclo.

## Tipo

- Documentação

**Comment by RochaCarla** [comment]
Onde está esse documento?

**Comment by Joranhezon** [comment]
[Aqui](https://fga-eps-mds.github.io/2018.2-ComexStat/docs/roadmap) :)
