### ISSUE TITLE
Estudar os conceitos de devops

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#17]
## Descrição

Estudar os conceitos gerais de devops e a aplicabilidade deles no nosso projeto. Documentar o estudo em página da wiki.

**Comment by viniciusoliveira96** [comment]
Os conceitos de Devops foram estudados, um documento sobre o tema será criado posteriormente e apresentado em página na wiki do projeto.
Sobre a aplicabilidade, e criação de componentes como o Docker, necessitamos antes da definição da linguagem utilizada no projeto.

**Comment by viniciusoliveira96** [comment]
O estudo está documentado e disponivel em https://fga-eps-mds.github.io/2018.2-GrupoMDIC/docs/devOps
