### ISSUE TITLE
Iniciar Documentação da API

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#174]
## Descrição

Eu, como desenvolvedor, gostaria de utilizar uma ferramenta para iniciar a documentação da api, de maneira a melhorar a organização do projeto e permitir que novos desenvolvedores tenham facilidade em entender a api produzida anteriormente.

## Tipo

- História Técnica

## Critérios de aceitação

- [ ] Utilizar o Sphinx para documentar;
- [ ] Criar "esqueleto" da documentação

**Comment by Joranhezon** [comment]
Foi decidido deixar essa issue para outra sprint, por existir muitas histórias complexas e importantes para essa sprint.

**Comment by rogerioo** [comment]
Issue foi solucionada com esse [PR](https://github.com/fga-eps-mds/2018.2-ComexStat/pull/207)
