### ISSUE TITLE
Transparência

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2018.2-GrupoMDIC#188]
Alguns pontos de melhorias

- [ ] o ambiente de homolog está indisponível (front)

- [ ] a documentacao nao está disponivel na branch principal (como está a comunicação)

- [x] Levantado questões relacionado ao cansaço da Equipe. Sugestão: equilibrar o planejamento das sprints com o escopo variável (diminuir o escopo, para que o projeto seja feito de forma mais equilibrado)

- [ ] Feedback: Os fatores envolvidos nisso são -jeito que a matéria é lecionada. Se puderem abrir uma issue com feedbacks e sugestões de melhoria, será muito bem vinda. Estou à disposição para conversar a respeito (faz parte das práticas ágeis feedback em relacao ao trabalho, inclusive o meu) :)

- [ ] Tentem se preocupar com a segurança das chaves - CODECOV_TOKEN=219366db-cfde-4936-967d-25072639f80f

- [x] Fechar as branches não utilizadas

- [ ] Issues - a qualidade das issues podem melhorar. Muitas vezes, os critérios de aceitacao se confundem com tarefas (e elas as vezes são genéricas) - Ex: #98 

- [ ] Pouco diálogo nas issues - muitas vezes não fica claro como a issue foi concluida (ex #150 )

- [x] Escopo desenvolvido até o momento está legal!

- [x] Cobertura de testes da API - OTIMO

- [x] Front - quem manda é o cliente ;)

**Comment by SannyaArvelos** [comment]
Na verdade é o ambiente de produção que está indisponível. Porque ainda não foi mergado com a master.
Obrigada pelo feedback :)

**Comment by Joranhezon** [comment]
Obrigado pelo feedback! Vamos nos atentar ao que pode ser melhorado e ao que está indisponível.

E obrigado especialmente por ter se importado em responder especificamente aos pontos sobre o cansaço da equipe e sobre o feedback da disciplina, é importante pro time saber que suas frustrações podem ser ouvidas e discutidas. Iremos abrir uma issue de sugestões na nossa próxima reunião, com certeza!
