### ISSUE TITLE
Realizar Treinamento Github Pages

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#19]
## Descrição 

Realizar treinamento de Github pages para os membros de MDS, visando uma melhoria na forma de documentação dos artefatos do projeto.

**Comment by viniciusoliveira96** [comment]
Treinamento realizado durante a reunião do dia 25/08.
Instrutores: Time de Eps
Participantes: @andrelucasf @MarcosNBJ @riquekaique @caioiobs @joao15victor08
