### ISSUE TITLE
Atualizar TODOS os documentos para R2

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#208]
## Descrição

Eu, como Scrum Master e Product Owner do comexstat, estou passando essa issue para o querido amigo Kaique pois estou com saudades dele e quero trabalhar ele até o ultimo minuto da release 2.

## Tipo

- HISTÓRIA CRITICA

**Comment by andrelucasf** [comment]
Vai que é tua @riquekaique

**Comment by rogerioo** [comment]
Chuta pro gol Kaicão!
@riquekaique

**Comment by SannyaArvelos** [comment]
Levou o time nas costas... @riquekaique

**Comment by rogerioo** [comment]
Era zueira mano, o @MarcosNBJ já salvou de novo!
