### ISSUE TITLE
Realizar treinamento de docker

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#22]
## Descrição

Realizar treinamento sobre instalação e utilização do docker

**Comment by fabiolamfleury** [comment]
@vinicinolivera durante essa semana, existe algum dia que o treino poderia ser feito?

**Comment by Joranhezon** [comment]
@vinicinolivera já tem uma data para o treinamento?

**Comment by viniciusoliveira96** [comment]
Definir junto ao time uma possivel data para o treinamento. Hoje, dia 06/09 teremos uma reunião para configuração das maquinas, e logo após definiremos a data do treinamento, podendo ser sexta, dia 07/09 ou sabádo 08/09.

**Comment by viniciusoliveira96** [comment]
Treinamento finalizado no dia 06/09, porém como nem todos os membros do tipo poderam participar, ao longo da proxima semana serão designadas várias atividades para os mesmos praticarem
