### ISSUE TITLE
Obter Código-fonte e Modelo Entidade-Relacionamento com o cliente

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#25]
## Descrição

Obter o código-fonte e o ME-R do Comexstat com o cliente, de maneira que seja possível possuir um entendimento melhor do que será feito no Comexserv.

- [x] Código-fonte
- [X] ME-R

**Comment by fabiolamfleury** [comment]
Passando para essa issue texto do cliente que também ajuda o entendimento do contexto:


"
Sugiro que vcs, além de testarem o ComexStats atual, também se inteirem sobre os dados do Siscoserv, do comércio exterior de serviços. Daí tem 3 coisas que podem lhes ajudar:

1. Página consolidada das Estatísticas de 2017 - http://www.mdic.gov.br/index.php/comercio-servicos/estatisticas-do-comercio-exterior-de-servicos/3330-estatisticas-do-comercio-exterior-de-servicos-2017 (experimento de reescrita desta página: https://mdicgovbr.github.io/pagina-estatisticas/)

2. O Siscoserv Dash possibilita filtros para análise dos dados - http://www.mdic.gov.br/portal/dashboard.html

3. A NBS - Nomenclatura Brasileira de Serviços - http://www.mdic.gov.br/index.php/comercio-servicos/a-secretaria-de-comercio-e-servicos-scs-13
"

**Comment by fabiolamfleury** [comment]
EXPLICAÇÃO DO MODELO DE DADOS (DIAGRAMA COMENTADO EM BREVE)

______________________________________________________________________
Modelar o banco de acordo com o modelo de dados apresentado pelo cliente
BANCO
Tabelas: Fatos, dimensões, 
Relações: O fato é uma maneira de normalizar os dados de um datawarehouse

Fatos(dados principais-4): imp(importação) exp(exportação) facilitação do raciocínio

Tabela fatos: campos de valor e peso, QUANTIDADE(fob) (definições de comércio de bens, campos principais). O resto é dimensão: temporais(ano, mês), unidade?(kiloVERIFICAR), RF(Unidade da Receita Federal - ignorar, VIA tbm ignorar), código de municipio, NCM->Nomeclatura comum do mercosul, 6 digitos SH são 8.Deve-se identificar em todo dado o NCM(as 3 tabelas de cima só existem no comexstat e são relacionados com o NCM, fazer um estudo sobre isso). Tabela de país(nada haver com UF, país de destino na exportação, bloco economico(agrupamento de país), ou o país de origem da importação) 

Os agrupamentos das 3 tabelas superiores está em relação à linguas(a RELAÇÃO COM O NCM É HIERÁRQUICO, os níveis são relacionados das 4 tabelas superiores), SÃO TODAS TABELAS FIXAS

FILTROS DO COMEXSTAT SÃO AS TABELAS QUE SE RELACIONAM COM O NCM, REPREESENTAM OS NÍVEIS DAS HIERARQUIAS SEÇÃO, CAPÍTULO,  POSIÇÃO, SUBPOSIÇÃO, NCM (HIERARQUIA DE INFORMAÇÃO, EXEMPLO ELETRODOMÉSTICO, NÍVEL MENOR: GELADEIRA)
Todo comércio (de exportação) uma pessoa no brasil(exportador, dado municipalizado) para uma outra pessoa no estrangeiro


SISCOMEX Alimenta os dados do banco
SISCOSERV

SISTEMA HARMONIZADO: Tipologia de bens internacional 

________________________________________________________________________
NO CASO DO BANCO DE SERVIÇOS

É obrigado usar o siscoserv no brasil, nos outros países não necessariamente, é usado um padrão internacional, diferente

NBS Nomeclatura brasileira de serviços(No LUGAR DO NCM), não existem recortes (como no caso do NCM, que gera as outras três tabelas), apesar de existir certo agrupamento desta forma nos serviços

O MODELO DE DADOS É MT PARECIDO, NÃO GUARDA O PESO DAS ENTRIES, UNIDADE, QUANTIDADE
A tabela de entries vai ser simplificada


NBC, CPC, EBOPS (tipo o do ncm, porém n é tão direto, simples) fazer “traduções” destas dismensões

**Comment by Joranhezon** [comment]
O código-fonte foi disponibilizado pelo cliente por meio de um .zip. Não se pode disponibilizar esse documento online, devido ao fato do cliente ser uma entidade pública.
