### ISSUE TITLE
Fazer a votação da data do rolê e do planejamento 

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#33]
## Descrição

Votação do dia e horário do planejamento(hangouts) e local e horário do rolê

**Comment by rogerioo** [comment]
Galera, almoço amanhã 12 hrs, **bora**?

@fabiolamfleury @Joranhezon @SannyaArvelos @vinicinolivera @caioiobs @riquekaique @MarcosNBJ @andrelucasf @joao15victor08 

Sugestões: São Paulo, que não é tão bom e mais conhecido; Churrasquinho do Ceará, que é mais gostoso e tem um melhor custo benefício.

**Comment by Joranhezon** [comment]
Amanhã eu não posso, pessoal. Irei viajar para São Paulo. Vocês podem fazer uma homengem à mim e irem no São Paulo. :)

**Comment by joao15victor08** [comment]
Por mim pode ser qualquer um.

**Comment by kaiquebuilds** [comment]
Não posso ir, mas deixo meu conselho: o Ceará tem um ótimo custo benefício. :D

**Comment by fabiolamfleury** [comment]
Na quinta no almoço ficaria melhor? Vamos tentar marcar um dia que a maioria possa galera, digam ai

**Comment by rogerioo** [comment]
Vamos ver na terça da semana que vem, o que acham?

Porque a galera já voltou de viagem!

**Comment by kaiquebuilds** [comment]
Acho uma ótima ideia @rogerioo, tô dentro!

**Comment by viniciusoliveira96** [comment]
Haha, hoje e amanhã para mim é complicado, mas topo terça que vem!

**Comment by fabiolamfleury** [comment]
Rolê transferido para sábado dia 15 pós reunião de planejamento
