### ISSUE TITLE
Fazer o protótipo de baixa fidelidade junto ao cliente

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#34]
## Descrição

Para melhor entendimento do produto que será desenvolvido, um protótipo de baixa fidelidade será feito em reunião com o cliente, no dia 03/09/2018.

**Comment by Joranhezon** [comment]
Não foi possível realizar o protótipo junto ao cliente, devido à quantidade de tópicos que tiveram que ser discutidos com ele. Por exemplo:

- Escopo do projeto;
- Manutenção do software já existente;
- Dados relacionados à bens e serviços

**Comment by fabiolamfleury** [comment]
Validado com o cliente na reunião de hoje, 17/09
