### ISSUE TITLE
Configurar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#35]
## Descrição

- [x] Realizar a configuração inicial do docker utilizando python django.

- [x] Criar a branch de desenvolvimento

**Comment by viniciusoliveira96** [comment]
Branch de desenvolvimento (develop) foi criada e a configuração do docker inicial do docker está em execução!

**Comment by viniciusoliveira96** [comment]
Configuração do Docker foi concluida, e ja dando inicio a parte inicial do projeto

**Comment by fabiolamfleury** [comment]
Devido a problemas na estruturação dos arquivos do projeto encontrados e ferramentas de desenvolvimento, estou reabrindo essa issue

**Comment by fabiolamfleury** [comment]
Resolvido no pr #51
