### ISSUE TITLE
Organização da arquitetura do projeto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#36]
## Descrição

Realizar pesquisa em relação a arquitetura de micro serviços relacionada a python django e data science. Documentar pesquisa, fazendo ainda diagramas para relacionar as tecnologias que serão utilizadas e como as camadas realizarão comunicação.

**Comment by fabiolamfleury** [comment]
Cliente sugeriu a tecnologia GraphQL (pode ou não ter integração com django, teria que ser verificado)

**Comment by fabiolamfleury** [comment]
@SannyaArvelos updates?

**Comment by fabiolamfleury** [comment]
Artigos:
- [Microservices – Please, don’t](https://blog.rapid7.com/2016/09/15/microservices-please-dont/)
- [Full Stack Python - Microservices](https://www.fullstackpython.com/microservices.html)
- [Graphene-Django](https://docs.graphene-python.org/projects/django/en/latest/)
- [Microservices - Martin Fowler](https://martinfowler.com/articles/microservices.html)
- [Why mimcroservices](https://dev.otto.de/2016/03/20/why-microservices/)
- [Building Django HTTP APIs with GraphQL and Graphene](https://www.techiediaries.com/django-graphql-tutorial/)

**Comment by fabiolamfleury** [comment]
Conversar com o cliente sobre as possiblidades:

Django REST
GraphQL - graphene-django


Os dois conseguem atender as requisições necessárias para buscar os dados do banco. Porém existem ressalvas:

- Usando REST, existem certas restrições ao utilizar filtros que utilizem outras tabelas que não a sendo pesquisada

- O GraphQl por ser mais flexível na utilização da api não possui ferramenta como swagger do django

![image](https://user-images.githubusercontent.com/20935369/45267978-81067b80-b44c-11e8-83d0-a39a744a35e5.png)
Então a utilização da api diretamente, caso seja necessária para o cliente, é um pouco diferente.

**Comment by Joranhezon** [comment]
Após a reunião com o cliente, foi decidido que será utilizado o GraphQL juntamente do Django.

**Comment by fabiolamfleury** [comment]
Explicando um pouco melhor essa decisão:

O GraphQL se adequa melhor ao contexto do grupo, não existe necessidade de outras operações que existem no rest como o post, delete, update... Será usado principalmente o query, do GraphQL, para fazer resgate de informações do banco de dados. Cogitou-se retirar o django e utilizar o flask com o graphql, que seria mais leve que o django, porém, o django possui uma estrutura mais interessante em relação a interface com o banco de dados e as operações disponíveis, bem como usa o postgresql, que é o mesmo banco de dados que já era usado no antigo sistema, o que facilita o reaproveitamento de dados.


Essas decisões foram feitas em conjunto com o cliente

**Comment by SannyaArvelos** [comment]
Tudo bem. E sobre o relacionamento das tecnologias tem um tópico que vou explicar melhor isso.
