### ISSUE TITLE
Montar Calendário com Provas de MDS/EPS

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#38]
## Descrição

Montar um calendário com as provas das disciplinas dos membros, de maneira à avaliar o risco que isso pode trazer ao time.

![image](https://user-images.githubusercontent.com/20935369/45267782-dee59400-b449-11e8-8167-3d474825a1ed.png)

![image](https://user-images.githubusercontent.com/20935369/45267785-f3299100-b449-11e8-84b4-0241e164f710.png)

**Comment by Joranhezon** [comment]
Não se esqueçam de comentar as datas de suas provas e momentos críticos em outras matérias, pessoal!

**Comment by kaiquebuilds** [comment]
@Joranhezon, não é melhor criar uma planilha no Drive? Tenho algumas disciplinas sem datas de prova definidas, seria mais fácil para atualizar.

**Comment by rogerioo** [comment]
Galera, eu criei um doc lá no drive, só preencher! ;)

**Comment by caioiobs** [comment]
Ok

**Comment by andrelucasf** [comment]
Okay

**Comment by joao15victor08** [comment]
Já preenchi lá.

**Comment by fabiolamfleury** [comment]
Atualizado 👍

**Comment by MarcosNBJ** [comment]
Feito

**Comment by kaiquebuilds** [comment]
Feito!

**Comment by rogerioo** [comment]
O documento com o calendário já está disponível no drive do time.
