### ISSUE TITLE
Criar a política de branchs do repositório

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#4]
## Descrição

Criar a política baseada no git flow.

**Comment by viniciusoliveira96** [comment]
A primeira versão do documento de política de branches que será seguido se encontra disponivel em: https://github.com/fga-eps-mds/2018.2-GrupoMDIC/wiki/Pol%C3%ADtica-de-Branches

**Comment by fabiolamfleury** [comment]
Será necessário transferir esse documento pras Github pages

**Comment by fabiolamfleury** [comment]
Sugestões:

- Colocar no documento políticas de commits
- Colocar identificadores de branch para documentação (doc/) e para configurações (tech/ ou config/)
- Documentar a existência da branch gh-pages para deploy das pages de docs

**Comment by fabiolamfleury** [comment]
Falta revisar os comentários feitos no pull request pra fechar essa issue!
