### ISSUE TITLE
Reuniões com o cliente

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#40]
## Descrição

Nesta issue serão documentadas as reuniões para garantir transparência e alinhamento do time quanto a visão do produto

A primeira reunião ficou documentada na issue #5

**Comment by fabiolamfleury** [comment]
# Reunião 03/09/2018

## Duração

16:30-18:50 (2h10)

## Membros Presentes

@Joranhezon 
@SannyaArvelos 
@vinicinolivera 
@fabiolamfleury
@MarcosNBJ 

## Decisões realizadas

- O time desenvolverá o sistema ComexStat (que já existe e foi estudado como modelo exemplo) utilizando novas tecnologias. Serão focos principais:
  - Usabilidade, já que o sistema atual é pouco intuitivo e a experiência do usuário (Ux) deixa a desejar
  - Estudo dos dados e filtros, para que possa entendê-los, otimizá-los e utilizar conceitos de data science para trazer dados de forma mais simples e mais fácil de visualizar.

O aplicativo será voltado para área de comércio de **bens**. Porém, há desejo do cliente de inserção dos dados de comércio de **serviços** futuramente na aplicação, então ela deve ser desenvolvida com o cuidado de compatibilidade.

- Foram definidos os usuários do sistema: **Gestores**. Pessoas produtoras de bens e serviços. Por exemplo: produtor de soja, advogado, construtores. Essas pessoas utilizam dados com que finalidade? (hipóteses que devem ser pesquisadas: competitividade de mercado, análise de nicho de mercado?) 
- Também foi explicado o modelo de dados que será usado na aplicação, que está detalhado em comentário na issue #25 .

- Requisitos mapeados:
  - Permalink das pesquisas, definir sintaxe de pesquisa de acordo com a construção da api (Exemplo: api.salic.cultura.gov.br);
  - Gerar pdf das consultas (Exemplo: plano.dados.planejamento.gov.br);
  - Gerar gráficos.
  - Embedding ao final na visualização de dados (Storytelling em data science)
  - Organizar o fluxo de experiência do usuário: Pesquisa ->Filtrar -> Agrupamentos -> Visualização de dados -> Compartilhar dados
  - Organizar a hierarquia de informação do sistema (Na filtragem, agrupamento e visualização é confusa no ComexStat);



## Detalhamento da Reunião

- Ideia do sistema ComexStat: abrigar conjuntamente dados bens e serviços juntos;
- Primeira atividade: entender os dados para depois conseguir fechar o escopo;
- O ComexStat não é intuitivo, seria possível criar um protótipo para melhoria do sistema ao propor melhorias de usabilidade do aplicativo de bens, conseguimos reutilizar o protótipo para a área de serviços;
- Foram analisadas possibilidades de continuidade do projeto: caso fizesse o projeto voltado para os dados de **serviços**, haveria o risco de não obtenção dos dados, já que o MDIC precisaria prepará-los antes de passar para o time, por questões de sigilo, ao contrário dos dados de **bens** que já passaram por esse processo e são de mais fácil acesso.
   - Proposta do PO:  utilizar dados proxy(fictícios) e desenvolver para os dados de serviços, deixando o comexstat atual de lado, ele seria utilizado apenas para levantamento de requisitos utilizando engenharia reversa.
  - Valor estratégico para o ministério seria muito maior de evolução do comex stat (comércio de bens) do que investir no serviço, que a equipe é menor e é uma área muito nova. Mas seria muito importante também possui espaço para "encaixar" comércio de serviços futuramente no sistema.
  - Caminho definido: fazer o sistema de bens, principal preocupação: usabilidade!
- Usuários do sistema(Power users!): produtores de bens e serviços. Exemplos: arquitetos, advogados, construtores.
- Sugestão de arquitetura https://graphql.org/learn/ -> arquitetura mais voltada para data science (vem depois de REST)
- Requisitos:
  - Permalink das pesquisas(#), definir sintaxe de pesquisa de acordo com a construção da api, paginação, na pesquisa de data usar um range…
  - Gerar pdf das consultas
  - Gerar gráficos
- Etapas do usuário: Repensar a sequência de dados, como eles são filtrados(primeiro dado-valores) semântica, filtros, ou agrupamentos (formulário básico e avançado)
  - Agrupar mês inicial e mês final seria um recorte avançado, deveria estar escondido
- Organizar o fluxo do usuário: o que ele quer pesquisar, depois quais filtragem, depois os agrupamentos e enfim a visualização de gráficos, e depois compartilhar (imprimir, gerar pdf, gerar csv, xslx)
- Gráfico por ano(seria interessante)
- Storytelling em data science (exemplo: jupyter notebook)
- Exemplo de api com permalinks api.salic.cultura.gov.br

**Comment by fabiolamfleury** [comment]
# Reunião 10/09/2018

## Duração

16:30-17:40 (1h00)

## Membros Presentes

@SannyaArvelos 
@fabiolamfleury

## Detalhamento da Reunião


Durante essa reunião, foi passado para o cliente os artefatos que foram finalizados e o andamento do projeto. Além disso, discutiu-se alguns requisitos que possuem impacto na decisão arquitetural do sistema.
- Pensando em implementação incremental, ao retirar as tabelas de nomeclatura, a de sh e a de ncm estão bem relacionadas e acopladas pela questão hierarquica do ncm.
- Não existe necessidade de autenticação no sistema
- Existe a necessidade de ORM (mapeamento de relacional-objeto, relação do banco para objeto, a nível de código) então talvez o django realmente ajude nesse trabalho
- Foi entregue o dumping do banco do comex stat (que está em postgresql) -> o django trabalha com postgre também
- Deseja-se expor a API do projeto futuramente, deve-se pensar na implementação com isso em consideração
- Depois de modelar o banco de dados da aplicação, deve-se validá-lo em reunião com o cliente(fazendo comparações)
- O cliente fará reuniões ainda essa semana para extração de informações do banco de serviços
- Querybuilder visual
- Focar primeiro na API, para conseguir utilizá-la independente da aplicação
- Além de visualizar gráficos, fazer comparações (extrapola a ideia de gráficos). Exemplo: Fazer duas filtragens, duas pesquisas ao mesmo tempo, para que elas sejam comparadas

**Comment by Joranhezon** [comment]
# Reunião 17/09/2018

## Duração

16:30-17:40 (1h00)

## Membros Presentes

@joranhezon 
@joao15victor08 

## Detalhamento da Reunião

Nessa reunião, foi mostrado para o cliente o trabalho realizado pela equipe na sprint anterior. Além disso, foram validadas as primeiras histórias de usuário e o protótipo de baixa fidelidade.

- Revisões foram feitas na escrita das histórias, principalmente no que se diz respeito aos atributos das models. Mais detalhes podem ser encontrados nas histórias de usuário alocadas para sprint 5.
- O cliente pediu que as histórias fossem escritas de forma a englobar um caráter mais técnico, tendo em vista que ele é um cliente técnico.
- O cliente apresentou o  [query builder](https://querybuilder.js.org/demo.html) um exemplo de funcionalidade e interface a ser seguido

**Comment by rogerioo** [comment]
Por chegar ao final do período do projeto proposto pela matéria, não serão realizadas mais reuniões com o cliente. Além disso outra abordagem foi tomada para o acompanhamento das reuniões após o último registro.
