### ISSUE TITLE
Trocar o nome do aplicativo nos documentos e adicionar nome novo do app

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#42]
## Descrição

Deve-se colocar o nome do aplicativo, decidido na reunião do dia 03/09, nos documentos já feitos.
 O documento se chama Comex Stat.

**Comment by andrelucasf** [comment]
Essa issue já poderia ter sido fechada!

**Comment by fabiolamfleury** [comment]
Já revisei os documentos também, aparentemente tá tudo certo!
