### ISSUE TITLE
Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-GrupoMDIC#44]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# ComexStat

- ## *Issues*

#### **Comunicação**

Vocês estão estão se comunicando bem nas *issues*, muito bom!

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Vocês não estão utilizando o sistema de pontuação nas issues, aqui tem alguns links pra ajudar nisso:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão com nomes bons. É interessante a prática de padronizar os nomes, eu recomendo utilizando os verbos no infinitivo. Os nomes devem ser claros e simples. Vocês estão fazendo um bom trabalho nisso!

#### ***Labels***

As Labels estão um pouco "pobres". Provavelmente eu faça um mini-guia para ajudar grupos que estão mal nisso, e consequentemente vai ajudar vocês!.

As issues de vocês são boas, só devem melhorar em alguns detalhes! (◕‿◕✿)

- ## Documentação

#### **Documento de Visão**

O documento de visão de vocês está bom, ele mostra bem o problema e a forma como a solução de vocês trabalha em cima disso.

#### **Documento de Arquitetura**

Eu acho que o documento de arquitetura de vocês é o microsserviços, então, sobre ele:

É interessante que vocês adicionem mais diagramas para uma compreensão maior da arquitetura.

#### **Documentação Geral**

A documentação de vocês tá bem interessante no que diz respeito ao documento de visão, mas não muito bom no de "arquitetura".
Não encontrei nenhuma informação em relação a documentação das sprints, e isso é bastante importate! Se não fizeram ainda corram atras disso.

- ## Considerações Finais

Vocês tem que melhorar em algumas coisas ainda, mas no geral vocês estão ok. Corram com o documento de arquitetura, pois ele é muito importante, e com as documentações de sprint, que são chave no desenvolvimento e avaliação do software. Assim que puder, atualizem o README de vocês com detalhes sobre o projeto!
Precisam corrigir alguns errinhos nas issues, mas estão no caminho certo! ◕‿◕

A Carla vai poder dar um feedback mais técnico pra vocês, mas espero ter ajudado na melhoria do
projeto de vocês de alguma forma. ( ⌒o⌒)人(⌒-⌒ )

[]s, @fepas

**Comment by rogerioo** [comment]
As melhorias sugeridas foram analisadas e realizadas. Agradecemos a contribuição!
