### ISSUE TITLE
Marcar reunião inicial com o cliente

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#5]

**Comment by Joranhezon** [comment]
A reunião foi marcada e realizada no dia 23/08, às 17:00 horas, no Ministério da Indústria, Comércio Exterior e Serviços.

Membros que participaram:
@joranhezon @fabiolamfleury @SannyaArvelos @vinicinolivera @MarcosNBJ @rogerioo @andrelucasf

**Comment by fabiolamfleury** [comment]
Ata da Reunião:

**Assunto discutido:**  Metodologia
**Próximas reuniões:** Segunda-feira 16-18h

- O Nitai sugeriu a divisão do projeto em três fases principais, conforme as atividades que já tinham sido descritas [nessa issue](https://github.com/fga-eps-mds/2018.2-GrupoMDIC/issues/2).São essas:
1. Criar container Docker para o sistema que já existe, Comex Stats e  estudar o modelo de dados do Comex Stats e os dados do Comércio de Serviços;
2. Adaptar o banco de dados para tratar de comércio de serviços ao invés de comércio de bens;
3. Adaptar Labels e textos para o contexto do comércio de serviços e incrementar com novos gráficos e funcionalidades.
- Também foi sugerido que o PO fosse um papel fora do time, para que a visão do projeto e do produto evitarem conflitos.
- Criação de grupo no telegram com o Nitai e o time (Feito durante a reunião!)
- Proposta de reuniões intercaladas, uma semana presencial e outra remota, porém na fase inicial do projeto apenas presenciais
- Sugestão de uso do quadro de emoções para acompanhamento do time
- O código do Comex Stats está sendo obtido pela equipe do MDIC para ser passada para nossa equipe, porém eles precisam fazer uma análise do aspecto de segurança antes disso
- Semana que vem serão disponibilizados então para equipe o modelo de banco de dados e o código
- O MDIC usa jenkins
- **O Comex Stat está escrito em PHP**
- O cliente não confirmou ainda se o nosso projeto será integrado como o Comex Stat ou o usará como modelo apenas
- **Qual será o nome do projeto?**



### Questionamentos:
1. Seria bom distanciar o cliente do processo, e reuniões serem para mostrar o trabalho feito e discutir próximas entregas(parte de requisitos, prazos etc)?
2. Propor pro cliente, fazer o sistema da parte de serviços separado, em sistema web, mas como pretendemos utilizar microsserviços, dizer da possibilidade de integração futura dos sistemas, caso necessário :)
Conversar com a Carla sobre essas indagações o quanto antes!
