### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by mbslet** [fga-eps-mds/2018.2-GrupoMDIC#61]
Galera, estou só dando uma olhada no repositório e vocês, bem show e a organização dos docs bem legal. 
Só não achei o documento de arquitetura, vocês têm?

**Comment by fabiolamfleury** [comment]
Olá! Nosso documento de arquitetura está em processo de revisão, no seguinte PR  #60

**Comment by mbslet** [comment]
Ah tranquilo! Obrigada :)

**Comment by rogerioo** [comment]
O documento está pronto neste [link](https://fga-eps-mds.github.io/2018.2-ComexStat/docs/docVisao).
