### ISSUE TITLE
Configurar gerência de migrações django do projeto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#63]
## Descrição

O django cria arquivos de migrações (na pasta migrations) em relação as models e o banco de dados. Caso não exista uma gerência disso, é perigoso com diferentes alterações em branchs e histórias acontecer de 

## Tipo

- História técnica

## Critérios de aceitação

- [ ] As migrações do app assets devem ser gerenciadas
- [ ] O projeto deve estar apto a receber novos apps django e já possuir gerenciamento de migrações

**Comment by rogerioo** [comment]
O gerenciamento proposto nessa issue foi solucionado, durante o desenvolvimento do projeto, de forma que as migrações de apps separados não são mais incluídos no repositório.
