### ISSUE TITLE
Definição dos micro serviços

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#69]
## Descrição

Definir como os micro serviços serão concretizados na aplicação

## Tipo

- Documentação

## Critérios de aceitação

- [x] Tirar dúvida com a carla

- [x] Documentar os micro serviços que serão feitos ou reutilizados

**Comment by SannyaArvelos** [comment]
Foi decidido juntamente com a Carla sobre a troca da arquitetura, visto que a arquitetura de microsserviços não se adequa ao nosso projeto. Temos um escopo bem acoplado por isso vamos utilizar bibliotecas externa para as funcionalidades da aplicação.

**Comment by SannyaArvelos** [comment]
Atualizei o documento de definição da arquitetura, de acordo com que foi conversado em sala.
