### ISSUE TITLE
Estudar os tutoriais propostos disponíveis no drive

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#7]
## Descrição

- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by kaiquebuilds** [comment]
- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by MarcosNBJ** [comment]
- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by joao15victor08** [comment]
- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by andrelucasf** [comment]
- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by caioiobs** [comment]
- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by rogerioo** [comment]
- [x] Metodologias ágeis
- [x] Git
- [x] MVC
- [x] Orientação a objetos

**Comment by fabiolamfleury** [comment]
Todos os membros realizaram os tutoriais dentro do período da sprint,
