### ISSUE TITLE
Montar o backlog do produto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#70]
## Descrição

Como um product owner, eu quero montar o product backlog para gerenciar os requisitos.

## Tipo

- Documentação

## Critérios de aceitação

- [x] Pontuar features
- [ ] Documentar épicos e features
- [x] Utilizar padrões de documentação de épicos e features
- [ ] Atualizar a EAP com os novos épicos

**Comment by fabiolamfleury** [comment]
Épicos novos rastreados na reunião de planejamento da sprint 5: análise de dados,  exposição da api(não funcional)

![image](https://user-images.githubusercontent.com/20935369/45624490-d2bc9080-ba60-11e8-8b55-89ded07bf232.png)


![image](https://user-images.githubusercontent.com/20935369/45624528-f41d7c80-ba60-11e8-81f3-7510d4419588.png)


![image](https://user-images.githubusercontent.com/20935369/45624559-0f888780-ba61-11e8-905c-c2bc7dba00bc.png)

**Comment by Joranhezon** [comment]
Adicionei um critério de aceitação para a issue. No caso, a atualização da EAP de acordo com os novos épicos

**Comment by fabiolamfleury** [comment]
@Joranhezon você linkou as features aos seus respectivos épicos?
