### ISSUE TITLE
Mapear possíveis reaproveitamentos de dados do dumping do sistema anterior

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#73]
## Descrição

Eu, como um desenvolvedor, quero recuperar os dados do dumping do sistema anterior para mapear possíveis reaproveitamentos.

## Tipo

- Histórica técnica

## Critérios de aceitação

- [x] Recuperar o banco de dados
- [ ] Criação de fixtures com dados relevantes
- [ ] Possível redução do volume do banco para agilizar o processo de desenvolvimento

**Comment by viniciusoliveira96** [comment]
Com o @rogerioo e  @joao15victor08 conseguimos recuperar os dados do banco para um arquivo .db, porém pela tamanho do mesmo estamos tendo algumas dificuldades em criar o dumping desses dados e passarmos serem utilizados no projeto para teste

**Comment by viniciusoliveira96** [comment]
Foi iniciado a criação dos dados ficticios, para que possamos fazer testes em desenvolvimento

**Comment by viniciusoliveira96** [comment]
Estamos analizando como fazer a redução do banco, para que melhore e que possamos puxar os dados para utiliza-los em nosso projeto
