### ISSUE TITLE
Fazer protótipo de alta fidelidade

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2018.2-GrupoMDIC#74]
## Descrição

Utilizar o protótipo de baixa fidelidade e validações com o cliente para criar o protótipo de alta fidelidade

## Tipo

- Documentação

## Critérios de aceitação

- [x] Tela Inicial, tela de filtros e agrupamentos, de visualização e compartilhamento de dados
- [ ] Validação com o cliente

**Comment by arthurbdiniz** [comment]
Eae glr sou um dos monitores de vcs, passando aqui rapidinho passar uma dica caso ainda não tenham decidido onde fazer o protótipo. Tem um site pra **desenvolver**, **testar** e **validar** protótipos muito bom chamado [Quant-UX](https://www.quant-ux.com). Recomendo darem uma olhadinha 👍🏼

**Comment by Joranhezon** [comment]
Obrigado pela dica!
