### ISSUE TITLE
Realizar Entrega Contínua

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#76]
## Descrição

Deve-se realizar a entrega contínua da aplicação, de maneira a garantir a existência de um ambiente de homologação e um ambiente de produção.

![Exemplo](https://user-images.githubusercontent.com/20938170/45751802-d7f91700-bbe9-11e8-8a9c-3e6929c78915.png)

## Features
- [ ] Configurar ambiente de homologação
- [ ] Configurar ambiente de produção

**Comment by rogerioo** [comment]
Todas as etapas necessárias para a realização desse épico foram cumpridas.
