### ISSUE TITLE
Criação da Usabilidade do Sistema

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#77]
## Descrição

Deve-se criar artefatos que descrevam como será feita a interação do usuário com o sistema. Para isso, alguns artefatos são de extrema importância, como por exemplo: protótipo de baixa fidelidade, a folha de estilo como um todo e o protótipo de alta fidelidade.

![image](https://user-images.githubusercontent.com/20938170/45752014-856c2a80-bbea-11e8-9c89-7d2ff76b7942.png)

## Features

- [ ] Criação de protótipos
- [ ] Definição da identidade visual

**Comment by rogerioo** [comment]
Todas as etapas necessárias para a realização desse épico foram cumpridas.
