### ISSUE TITLE
Configurar Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#78]
## Descrição

Deve-se realizar a configuração de um Docker para o projeto.

![image](https://user-images.githubusercontent.com/20938170/45752224-265ae580-bbeb-11e8-9507-c7de38074ab6.png)

## Features

- [ ] Configuração de Docker

**Comment by fabiolamfleury** [comment]
#102

**Comment by rogerioo** [comment]
Todas as etapas necessárias para a realização desse épico foram cumpridas.
