### ISSUE TITLE
Visualização de Dados Referentes à Comércio de Bens e Prestação de Serviços

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#79]
## Descrição

![image](https://user-images.githubusercontent.com/20938170/45752829-24922180-bbed-11e8-8959-d238b57633e8.png)

## Features

- [ ]
- [ ]

**Comment by rogerioo** [comment]
Como requisitado pelo cliente, o FrontEnd foi descontinuado.
