### ISSUE TITLE
Busca de Dados Referentes à Comércio de Bens e Prestação de Serviços

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#80]
## Descrição

![image](https://user-images.githubusercontent.com/20938170/45753187-64a5d400-bbee-11e8-97ea-cc6a225c2288.png)

## Features

- [ ]
- [ ]

**Comment by rogerioo** [comment]
Todas as etapas necessárias para a realização desse épico foram cumpridas.
