### ISSUE TITLE
Análise de Dados Referentes à Comércio de Bens e Prestação de Serviços

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#82]
## Descrição

![image](https://user-images.githubusercontent.com/20938170/45753447-48eefd80-bbef-11e8-8c0e-a0201f48395b.png)

## Features

- [ ]
- [ ]

**Comment by rogerioo** [comment]
A API já possibilita a pesquisa e análise dos dados pelo usuário.
