### ISSUE TITLE
Visualização de dados de bens por meio de tabelas 

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#87]
## Descrição

Feature relacionada às tabelas que devem ser geradas para visualização de dados de bens.

## Critérios de aceitação

- [x] Deve ser possível visualizar tabelas a partir de apenas algumas informações essenciais, como um resumo, que extraiam as informações mais relevantes
- [x] Deve ser possível visualizar tabelas com informações completas
- [ ] As tabelas devem exibir informações das tabelas de fatos de importação e exportação de bens, bem como tabelas de nomenclatura, origem, destino e via, a depender da seleção do usuário

**Comment by rogerioo** [comment]
Parte das issues foram implementadas, mas os requisitos da feature não foram completamente atendidos por conta do FrontEnd ter sido descontinuado.
