### ISSUE TITLE
Visualização de dados de bens por meio de gráficos

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#89]
## Descrição

Feature relacionada à visualização de dados de bens por meio de gráficos.

## Critérios de aceitação

- [ ] Deve ser possível visualizar gráficos a partir de apenas algumas informações essenciais, como um resumo, que extraiam as informações mais relevantes
- [ ] Mais de um tipo de visualização em gráfico deve ser disponibilizado, com o intuito de facilitar a interpretação de dados de bens para gestor
- [ ] Devem ser gerados gráficos que permitam acompanhamento de dados de bens em determinados períodos de temp

**Comment by rogerioo** [comment]
Ideia descontinuada pelo cliente por opção de não evoluir o FrontEnd.
