### ISSUE TITLE
Busca de dados de bens utilizando filtros

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#91]
## Descrição

Feature relacionada à utilização de filtros na busca de dados relacionados à comércio de bens.

## Critérios de aceitação

- [x] Separação dos dados por meses, de maneira a se escolher o ano e mês inical e o ano e mês final da busca
- [x] Agrupamento por meio de blocos econômicos
- [x] Visualização de dados por Net Weight ou valor em dólar

**Comment by rogerioo** [comment]
Feature implementada com todos os requisitos solicitados.
