### ISSUE TITLE
Busca de dados de serviços utilizando agrupamentos

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#92]
## Descrição

Feature relacionada à utilização de filtros na busca de dados relacionados à prestação de serviços.

## Critérios de aceitação

Não existem critérios ainda para essa feature.

- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by rogerioo** [comment]
Feature implementada com todos os requisitos solicitados.
