### ISSUE TITLE
Exportação de dados de bens

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#93]
## Descrição

A feature está relacionada a possibilidade de se poder compartilhar as pesquisas e dados adquiridos

## Critérios de aceitação

- [ ] O usuário conseguir exportar em formato PDF
- [x] O usuário conseguir exportar em formato csv
- [ ] O usuário conseguir exportar em formato embutido para colocar em seu site

**Comment by rogerioo** [comment]
Parte das issues foram implementadas, mas os requisitos da feature não foram completamente atendidos por conta do FrontEnd ter sido descontinuado.
