### ISSUE TITLE
Links de Dados de Bens

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#94]
## Descrição

Exemplo: Como um usuário, eu quero procurar por meus clientes pelos seus primeiros e últimos nomes.

## Tipo

- Tipo (possíveis: história de usuário, história técnica, documentação)

## Critérios de aceitação

- [x] As pesquisas devem direcionar para uma página própria, utilizando permalinks, para que o usuário consiga acessar a mesma pesquisa, os mesmos filtros, apenas a partir da url

**Comment by rogerioo** [comment]
Issue resolvida com o esse [pr](https://github.com/fga-eps-mds/2018.2-ComexStat-FrontEnd/pull/15) do Frontend.
