### ISSUE TITLE
Estudar os dados de comércio de bens

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#97]
## Descrição

Feature relacionada aos estudos de dados por meio de análise.

## Critérios de aceitação

- [x] O time deve estar alinhado em relação aos conceitos das tabelas no banco de dados e seus devidos campos
- [x] O time deve estar alinhado em relação aos conceitos dos relacionamento entre as tabelas do banco

**Comment by rogerioo** [comment]
Por já está em processo final do desenvolvimento, o time estudou por diversas vezes o banco do MDIC e suas necessidades de forma a modelar o banco de acordo com a realidade.
